name: example
description: Example project for the flutter_translate_fix library
publish_to: 'none'
version: 2.1.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate_fix:
    path: ../

  cupertino_ui: any
  material_ui: any
flutter:

  uses-material-design: true
  assets:
    - assets/i18n/
